---
# tasks file for roles/opensuse/install-vsftpd
- name: Install vsftpd service
  become: yes 
  zypper: 
    name: vsftpd
    state: latest
    update_cache: yes

- name: change the state of firewall
  become: yes
  service: 
    name: firewalld
    state: stopped
    enabled: no

- name: start the vsftpd 
  become: yes 
  service: 
    name: vsftpd 
    state: started
    enabled: yes
