---
# tasks file for roles/ubuntu/lamp
- name: Installing apache web server
  apt:
    name: apache2
    state: present

- name: starting services
  service: 
    name: apache2
    state: started

- name: allow access to tcp port 80
  ufw: 
    rule: allow
    port: '80'
    proto: tcp

- name: Enable firewall
  ufw: 
    state: enabled

- name: Installing mysql
  apt:
    name: mysql-server
    state: present

- name: Installing php
  apt: 
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Installing pre-requisites
  apt: 
    name: mariadb-server-10.3
    state: present
