---
# tasks file for roles/centos/nagios
- name: Install httpd 
  become: yes
  yum:
    name: httpd
    state: present 
    update_cache: yes

- name: Installing dependecies
  yum: 
    name: 
      - perl
      - gcc
      - glibc
      - glibc-common
      - unzip
      - gd 
      - gd-devel
      - postfix
    state:  present

- name: Add group in nagios
  become: yes
  group: 
    name: "{{ group }}"
    state: present

- name: Add user in nagios
  become: yes
  user: 
    name: "{{ user1 }}"
    group: "{{ group }}"

- name: Add also user in nagios
  become: yes
  user:
    name: "{{ user2 }}"
    group: "{{ group }}"

- name: Install nagios
  become: yes
  unarchive: 
    src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp
    remote_src: yes

- name: configure nagios
  become: yes
  command: ./configure --with-command-group=nagiosxi
  args: 
    chdir: /tmp/nagios-4.4.5

- name: Make clean
  make: 
    target: clean
    chdir: /tmp/nagios-4.4.5

- name: make all
  make:
    target: all
    chdir: /tmp/nagios-4.4.5
  
- name: Make install-init
  make: 
    target: install-init
    chdir: /tmp/nagios-4.4.5

- name: make install-daemoninit
  make:
    target: install-init
    chdir: /tmp/nagios-4.4.5

- name: Make install-commandmode
  become: yes
  make: 
    target: install-commandmode
    chdir: /tmp/nagios-4.4.5

- name: make install-webconf
  become: yes
  make: 
    target: install-webconf
    chdir: /tmp/nagios-4.4.5

- name: Install passlib
  pip: 
    name: passlib

- name: create user in nagios
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: user
    password: password

- name: Restart httpd
  service: 
    name: httpd
    state: restarted
    enabled: yes
