---
# tasks file for roles/ubuntu/install-vsftpd
- name: Installing of vsftpd for ubuntu
  become: yes
  apt: 
    name: 
      - vsftpd
      - ufw
    state: latest
    update_cache: yes 

- name: start the vsftpd service
  become: yes 
  service: 
    name: vsftpd
    state: started
    enabled: yes
