---
# tasks file for roles/ubuntu/install-vsftpd
- name: Installing of vsftpd for ubuntu
  become: yes
  apt: 
    name: vsftpd
    state: latest
    update_cache: yes 

- name: change the state of the firewall
  become: yes 
  service: 
    name: ufw
    state: stopped
    enabled: no

- name: start the vsftpd service
  become: yes 
  service: 
    name: vsftpd
    state: started
    enabled: yes
