---
# tasks file for roles/centos/config-vsftpd
- name: add denyUser
  become: yes 
  lineinfile: 
    path: /etc/ssh/sshd_config
    line: "DenyUser {{ ftp_user}}"
  register: sshd_config

- name: ftp directory creating...
  become: yes
  file:
    path: /home/Final-Exam/ftp
    state: directory
    owner: '{{ ftp_user }}'
    group: '{{ ftp_user }}'
    mode: '0555'

- name: files directory creating...
  become: yes
  file: 
    path: /home/Final-Exam/Files
    state: directory
    owner: '{{ ftp_user }}'
    group: '{{ ftp_user }}'
    mode: '0555'

- name: copy vsftpd.conf
  become: yes
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  register: vsftpd_config

- name: Restart vsftpd
  become: yes
  service:
    name: vsftpd
    state: restarted
  when: vsftpd_config.changed
