---
# tasks file for roles/ubuntu-monitor/elk
- name: Adding gpg key 
  become: yes 
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Adding the source
  become: yes 
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Updating ubuntu 
  become: yes 
  apt: 
    upgrade: 'yes'
    update_cache: yes

- name: Installing elastic search
  become: yes
  apt: 
    name: elasticsearch
    state: present

- name: Installing kibana
  become: yes 
  apt: 
    update_cache: yes
    name: kibana
    state: present

- name: Installing logstash
  apt: 
    name: logstash
    state: present
