---
# tasks file for roles/centos/lamp
- name: installing apache web server
  dnf:
    name: httpd
    state: present

- name: starting httpd service
  service: 
    name: httpd
    state: started

- name: Enabling firewalld
  firewalld: 
    service: http
    permanent: yes
    state: enabled

- name: Installing mariadb
  dnf: 
    name: mariadb-server
    state: present

- name: starting mariadb service 
  service: 
    name: mariadb
    state: started
    enabled: yes

- name: installing php
  dnf: 
    name: 
      - php
      - php-mysqlnd
    state: present

- name: Restarting httpd service
  service:
    name: httpd
    state: restarted
